In [1]:
#ARNAB GOSWAMI
#ROLL-PG/SOBAS/13/24/005
#ENROLLMENT NUMBER- AU/2024/0001647
#MSC PHYSICS SEM2
#Q1-9
import torch
import numpy as np

In [2]:
r=torch.rand(5,5)
print(r)

tensor([[0.7987, 0.9428, 0.2094, 0.0910, 0.4464],
        [0.3300, 0.3390, 0.8003, 0.4212, 0.7541],
        [0.9458, 0.5145, 0.8828, 0.8626, 0.1481],
        [0.7599, 0.1767, 0.3855, 0.0933, 0.5264],
        [0.3240, 0.9167, 0.8081, 0.1384, 0.3444]])


In [3]:
a=torch.tensor([1,1,1])
d=torch.diag(a)
print(d)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])


In [4]:
a=np.array([1,2,3,4])
d=torch.from_numpy(a)

In [5]:
m1=torch.tensor([[1,2,3],[4,5,6],[2,3,4]])
m2=torch.tensor([[7,8,9],[10,11,12],[5,6,7]])

In [6]:
add=m1+m2
sub=m1-m2
mult=torch.mm(m1,m2)
div=torch.div(m1,m2)
print(add,"\n",sub,"\n",mult,"\n",div)

tensor([[ 8, 10, 12],
        [14, 16, 18],
        [ 7,  9, 11]]) 
 tensor([[-6, -6, -6],
        [-6, -6, -6],
        [-3, -3, -3]]) 
 tensor([[ 42,  48,  54],
        [108, 123, 138],
        [ 64,  73,  82]]) 
 tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000],
        [0.4000, 0.5000, 0.5714]])


In [7]:
a1=torch.tensor([1,2,3])
a2=torch.tensor([4,5,6])
d=torch.dot(a1,a2)
d

tensor(32)

In [8]:
r1=torch.rand(2,3)
r2=torch.rand(3,2)
print(r1,"\n")
print(r2,"\n")
d=torch.mm(r1,r2)
d

tensor([[0.1464, 0.9721, 0.7310],
        [0.3273, 0.6373, 0.1328]]) 

tensor([[0.4894, 0.9931],
        [0.1137, 0.9323],
        [0.3465, 0.3917]]) 



tensor([[0.4354, 1.3379],
        [0.2786, 0.9712]])

In [9]:
r=torch.rand(6,6)
m=r.view(3,2,6)
m

tensor([[[0.4496, 0.6836, 0.2990, 0.5316, 0.7221, 0.5602],
         [0.2069, 0.7430, 0.0891, 0.2588, 0.0198, 0.5073]],

        [[0.2488, 0.0477, 0.7586, 0.8600, 0.7735, 0.3029],
         [0.8961, 0.6068, 0.1381, 0.8742, 0.9280, 0.3967]],

        [[0.9806, 0.6219, 0.7548, 0.9647, 0.7119, 0.9484],
         [0.4677, 0.7042, 0.2921, 0.3274, 0.1482, 0.4962]]])

In [10]:
v=torch.tensor([1,2,3])
stack=torch.stack((v,v,v))
stack

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [11]:
m1=torch.tensor([[1,2,3],[4,5,6],[2,3,4]])
m2=torch.tensor([[7,8,9],[10,11,12],[5,6,7]])
conc_tensor=torch.cat((m1,m2),dim=1)
conc_tensor

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12],
        [ 2,  3,  4,  5,  6,  7]])

In [12]:
x=torch.tensor(2.0,requires_grad=True)
y=torch.tensor(3.0,requires_grad=True)

In [13]:
z=x**2+y**2+2*x*y
z.backward()